### ISSUE TITLE
Support intersection

### ISSUE THREAD

**Issue by kishorenc** [cruppstahl/for#1]
Thanks for making `libfor` available! Adding intersection support would be very useful. Right now, I have to unpack the compressed array and do intersections. Is it technically possible to do that without unpacking the ints?

**Comment by lemire** [comment]
@kishorenc Though it does not directly answer your very valid question, you might want to check out CRoaring https://github.com/RoaringBitmap/CRoaring if you care about intersections over compressed data.

**Comment by kishorenc** [comment]
@lemire I'm familiar with RoaringBitmap (I've also used EWAH before). For this application, I also need a way to know the index location of a given value in the set (`libfor` has [`for_lower_bound_search`](https://github.com/cruppstahl/libfor/blob/49611808d08d4e47116aa2a3ddcabeb418f405f7/for.h#L257)) - is there a way to do that in Roaring?

**Comment by cruppstahl** [comment]
Hi Kishore,
I'm happy that you can make good use of libfor! But I don't have an idea how to implement the intersection efficiently without unpacking...

**Comment by lemire** [comment]
@kishorenc CRoaring does support rank and select functions.

**Comment by kishorenc** [comment]
@cruppstahl No problem, closing this issue for now.

@lemire Thank you - `rank` is exactly what I'm looking for.
